# Generated by Django 2.1.5 on 2021-08-02 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movielists',
            name='id',
        ),
        migrations.AlterField(
            model_name='movielists',
            name='movieid',
            field=models.CharField(max_length=15, primary_key=True, serialize=False, unique=True),
        ),
    ]
